### ISSUE TITLE
Make gh-pages the default

### ISSUE THREAD

**Issue by bnjbvr** [PeterJensen/mandelbrot#9]
Hi,

I just realized my recent modifications were not added to the github pages, as these live inside the gh-pages branch, and my PR was onto master. To avoid this kind of confusion in the future, I propose that the gh-pages be the default and that the master branch gets removed.

Default branch for a repo can be set in the settings of a given repository (from https://github.com/PeterJensen/mandelbrot this is in Settings, then default branch, right under the name repository).
Deleting a branch can be done in https://github.com/PeterJensen/mandelbrot/branches .

@PeterJensen what do you think?

**Comment by PeterJensen** [comment]
Hi Benjamin,

I prefer to keep the master branch around.  Just because pretty much all github repos have a master branch, if I delete it the 'casual' user will probably get confused.  Lots of git commands implicitly assume you're working on the master branch, I think.  For now, I'll just merge your changes into the gh-pages branch.

Is that OK with you?

**Comment by PeterJensen** [comment]
I see, that you just did that merge yourself ea0cfb2310406b482b12f56405f6c316431deecd

**Comment by PeterJensen** [comment]
I see that you already merged the pull request: PeterJensen/fbird#2, so I'm closing this issue.
